apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kaimen-admin-frontend.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kaimen-admin-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kaimen-admin-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kaimen-admin-frontend.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: dockersecret
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      restartPolicy: Always
