apiVersion: v1
kind: Secret
metadata:
  name: dockersecret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: |
    {{- $registry := .Values.imagePullSecrets.registry }}
    {{- $username := .Values.imagePullSecrets.username }}
    {{- $password := .Values.imagePullSecrets.password }}
    {{- $auth := printf "%s:%s" $username $password | b64enc }}
    {{- $json := printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" $registry $username $password $auth | b64enc }}
    {{ $json }}
