apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ingress.tlsSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kaimen-admin-frontend.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.tlsCrt | b64enc }}
  tls.key: {{ .Values.ingress.tlsKey | b64enc }}
