name: Build, Push and Deploy Frontend

on:
  push:
    branches: [main, develop]

env:
  REGISTRY: kaimen-hk.tencentcloudcr.com
  IMAGE_NAME: management.platform.frontend/kaimen-admin-frontend

jobs:
  build-and-push:
    if: ${{ github.ref == 'refs/heads/develop' }}
    runs-on: ["self-hosted", "HK"]
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Tencent Cloud TCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.TCR_USERNAME }}
          password: ${{ secrets.TCR_PASSWORD }}

      - name: Extract metadata (tags, labels) for dev
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            BUILD_MODE=dev
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Set IMAGE_TAG environment variable
        run: |
          TAG=$(echo "${{ steps.meta.outputs.tags }}" | tail -n1)
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV

      - name: Update Helm values.yaml with commit tag
        run: |
          echo "Updating charts/kaimen-frontend/values.yaml with image tag $IMAGE_TAG"
          yq e ".image.tag = \"${IMAGE_TAG##*:}\"" -i charts/kaimen-frontend/values.yaml

      - name: Commit updated values.yaml (skip CI)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add charts/kaimen-frontend/values.yaml
          git commit -m "Update kaimen-frontend image tag to ${IMAGE_TAG##*:} [skip ci]" || echo "No changes to commit"
          git push origin develop

  deploy-to-develop:
    name: Deploy to Dev Environment
    if: ${{ github.ref == 'refs/heads/develop' }}
    needs: build-and-push
    runs-on: [self-hosted, HK]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Determine image tag from current commit
        run: |
          echo "IMAGE_TAG=${{ github.sha }}" >> $GITHUB_ENV

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Configure KUBECONFIG from secret
        run: |
          echo "${{ secrets.KUBECONFIG }}" > /tmp/kubeconfig
          yq e '(.contexts[].context.user) |= tostring | (.users[].name) |= tostring' -i /tmp/kubeconfig
          mkdir -p $HOME/.kube
          mv /tmp/kubeconfig $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Verify kubectl connection
        run: kubectl cluster-info

      - name: Deploy with Helm (frontend dev)
        run: |
          helm upgrade --install kaimen-admin-frontend-dev ./charts/kaimen-frontend \
            --namespace kaimen-admin-dev --create-namespace \
            --set-string imagePullSecrets.username='${{ secrets.TCR_USERNAME }}' \
            --set-string imagePullSecrets.password='${{ secrets.TCR_PASSWORD }}' \
            --set-string ingress.tlsCrt='${{ secrets.INGRESS_TLS_CRT }}' \
            --set-string ingress.tlsKey='${{ secrets.INGRESS_TLS_KEY }}' \
            --set-string config.ENVIRONMENT=development
